// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9VCX0BfsNvyWMOrkQUHxWCzbqS84NGM',
    appId: '1:388706912604:web:b6084fbc4ffb4ba3779999',
    messagingSenderId: '388706912604',
    projectId: 'whatsai-9e093',
    authDomain: 'whatsai-9e093.firebaseapp.com',
    storageBucket: 'whatsai-9e093.appspot.com',
    measurementId: 'G-17R85BZCTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyglNoG_ALojYrHnvMRQSokvnjausii8',
    appId: '1:388706912604:android:e29660b0f104cc14779999',
    messagingSenderId: '388706912604',
    projectId: 'whatsai-9e093',
    storageBucket: 'whatsai-9e093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPYh_5o3zNpaoRBLE7YuA-568m-Fl-WI',
    appId: '1:388706912604:ios:6fcd169029458b10779999',
    messagingSenderId: '388706912604',
    projectId: 'whatsai-9e093',
    storageBucket: 'whatsai-9e093.appspot.com',
    iosBundleId: 'com.example.whatsAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPYh_5o3zNpaoRBLE7YuA-568m-Fl-WI',
    appId: '1:388706912604:ios:ebc35e8199cc20ec779999',
    messagingSenderId: '388706912604',
    projectId: 'whatsai-9e093',
    storageBucket: 'whatsai-9e093.appspot.com',
    iosBundleId: 'com.example.whatsAi.RunnerTests',
  );
}
